### ISSUE TITLE
Rename+export bind?

### ISSUE THREAD

**Issue by jw3126** [goretkin/FixArgs.jl#3]
I really like the `bind` function and would like to export it. Unfortunately its name clashes with `Base.bind`:
```julia

help?> bind
search: bind binomial BigInt begin SubString bitstring disable_sigint reenable_sigint SubstitutionString AbstractString AbstractUnitRange AbstractIrrational

  bind(chnl::Channel, task::Task)
...
```
So I think it is a good idea to rename `bind` and `@bind`. Some possible names: `curry, fix, partial, fixargs, bindargs`

**Comment by goretkin** [comment]
I like `fix`, and maybe also renaming `Bind` to `Fix`, too. Makes the connection to `Base.Fix1`and `Base.Fix2` clear.

I like `partial`, too. Though I'm sure there are packages that use `partial` to mean "partial derivative", so perhaps it's best to avoid it.

I named the package `Curry`, but as far as I know, it's really about partial application: https://stackoverflow.com/a/23438430/415404 .

**Comment by jw3126** [comment]
Ah thanks, I did not know what currying really meant until now.

**Comment by goretkin** [comment]
What do you think of `Fix`, `fix`, `@fix`?

**Comment by jw3126** [comment]
I like fix.
