### ISSUE TITLE
Version released to Pkg is old

### ISSUE THREAD

**Issue by clintonnolan** [goretkin/FixArgs.jl#30]
After watching your JuliaCon talk, I tried to replicate what you were doing with `using FixArgs` and most of it didn't work.

I looked into the reason for this, and it turns out a quite old commit is the one released to Pkg.

It's especially important to make a release since there's already something up on Pkg.

You should probably make a tag/release here too.

**Comment by goretkin** [comment]
You are right. Part of the problem is that FixArgs relies on an unreleased https://github.com/ararslan/FrankenTuples.jl/ if I recall correctly.

Do you know how to use an unreleased version of the package? If not, I can help you with that in the meantime.

**Comment by clintonnolan** [comment]
Hmm, it looks like FrankenTuples needs to be released if you want to use it as a dependency.

You may be able to release FrankenTuples if you're a collaborator, or otherwise one of us could ask @ararslan if they'd release FrankenTuples to JuliaHub.

Both projects don't need a tag/release on Github, apparently JuliaHub will accept any commit as the basis for a Julia release, though it might be good practice to do so.

**Comment by ararslan** [comment]
https://github.com/JuliaRegistries/General/pull/42416

**Comment by goretkin** [comment]
https://github.com/JuliaRegistries/General/pull/63364#issuecomment-1170422789
