### ISSUE TITLE
Macros to facilitate expressing types in methods

### ISSUE THREAD

**Issue by goretkin** [goretkin/FixArgs.jl#9]
reference: https://github.com/goretkin/FixArgs.jl/pull/8#discussion_r461929151

e.g. a macro such that

```julia
@evaltype function bounding(::Type{>:UnitRange}, _union::(@FixT union UnitRange{T} UnitRange{T})) where T <: Integer
[...]
end
```

expands to

```julia
function bounding(::Type{>:UnitRange}, _union::Fix{typeof(union), Tuple{Some{UnitRange{T}}, Some{UnitRange{T}}}, NamedTuple{(),Tuple{}}}) where T <: Integer
[...]
end
```

Could be written just as one macro on the whole function definition, but that itself is seemingly decomposable into two pieces, one of which (`@evaltype`) might generally be useful outside of `FixArgs.jl`.

:($(:(Complex{T})) where {T})

**Comment by jw3126** [comment]
It makes me sad, that we need to do this, but yeah I guess there is really a need for macros here. But do we really need two of them? Maybe the following would actually suffice?
```julia
@macroexpand @FixT f(::typeof(union), ::UnitRange{T}, ::UnitRange{T})
Fix{typeof(union), Tuple{Some{UnitRange{T}, UnitRange{T}}, Any}
```

**Comment by goretkin** [comment]
I don't see where `bounding` comes into your example.

Anyway, like I said, it could be written with one macro. I just mentioned the decomposition because it seems like a worthwhile idea.

**Comment by jw3126** [comment]
```julia
function bounding(::Type{>:UnitRange}, _union::(@FixT union UnitRange{T} UnitRange{T})) where T <: Integer
[...]
end
```

**Comment by goretkin** [comment]
I assumed making this work with the type parameters would be problematic, but it looks like it is all fine!

e.g.

```julia
using Test: @test
macro Foo()
    return :(Complex{Int64})
end

macro Foo2(T)
    return :(Complex{$(esc(T))})
end

bar(x) = "fallback"
bar(x::(@Foo)) = "dispatch @Foo"
@test bar("") == "fallback"
@test bar(1+2im) == "dispatch @Foo"

bar2(x) = "fallback"
bar2(x::(@Foo2 Int64)) = "dispatch @Foo2 Int64"
bar2(x::(@Foo2 Float64)) = "dispatch @Foo2 Float64"
@test bar2(1 + 2im) == "dispatch @Foo2 Int64"
@test bar2(1 + 2.0im) == "dispatch @Foo2 Float64"

bar3(x) = "fallback"
bar3(x::(@Foo2 T)) where {T} = "dispatch @Foo2 T, where T = $T"
@test bar3(1 + 2im) == "dispatch @Foo2 T, where T = Int64"
@test bar3(1 + 2.0im) == "dispatch @Foo2 T, where T = Float64"

# double check
@show @macroexpand bar3(x::(@Foo2 T)) where {T}
```

**Comment by goretkin** [comment]
I believe the definition of this macro should be based on this "rule", e.g.

```julia
typeof(FixArgs.@fix union([1], [2])) == FixArgs.@FixT union(::Vector{Int64}, ::Vector{Int64})
```

And it should probably also handle `_`. It should not handle keyword arguments.

I actually am glad there is a macro for this. It is nicely parallel.

`foo(1 / 2)` dispatches to `foo(::Float64)`
`foo(@fix 1 / 2)` dispatches to `foo(::(@FixT ::Int64 / ::Int64))`

I wonder if there are any suggestions to improve upon the `FixT` name.

**Comment by goretkin** [comment]
`@xquoteT` is this (and probably the name should still be improved).
